# .github/workflows/deploy.yml
name: Deploy to Unraid Server
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, unraid-paul-blake]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          load: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/paul-blake-site:latest
            ${{ secrets.DOCKER_USERNAME }}/paul-blake-site:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RAW }}

      - name: Deploy to Unraid Server
        run: |
          set -e # Exit immediately if a command exits with a non-zero status
          
          # Add Unraid host to known_hosts to prevent interactive prompt
          ssh-keyscan -H ${{ secrets.UNRAID_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Use SSH to execute commands on Unraid
          ssh ${{ secrets.UNRAID_USERNAME }}@${{ secrets.UNRAID_HOST }} << 'EOF'
            set -e
            echo "--- Navigating to project directory ---"
            cd /mnt/user/appdata/paul-blake-website/
            
            echo "--- Pulling latest image from Docker Hub ---"
            docker compose pull paul-blake-website # <-- THE ONLY CHANGE IS ON THIS LINE
            
            echo "--- Restarting container with new image ---"
            docker compose up -d
            
            echo "--- Cleaning up old images ---"
            docker image prune -f
            
            echo "--- Deployment completed successfully! ---"
          EOF
