# .github/workflows/deploy.yml
name: Deploy to Unraid Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, unraid-paul-blake]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          load: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/paul-blake-site:latest
            ${{ secrets.DOCKER_USERNAME }}/paul-blake-site:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Decode SSH Private Key
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          # Decode the base64 secret and save it to a temporary file
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa_github_actions
          # Set correct permissions for the private key (CRITICAL!)
          chmod 600 ~/.ssh/id_rsa_github_actions
        shell: bash
        
      - name: Deploy to Unraid Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UNRAID_HOST }}
          username: ${{ secrets.UNRAID_USERNAME }}
          # Now reference the path to the decoded private key file
          key: ~/.ssh/id_rsa_github_actions # <--- CHANGE THIS LINE
          script: |
            # Navigate to project directory
            cd /mnt/user/appdata/paul-blake-website/
            
            # Pull the latest image from Docker Hub
            docker compose pull paul-blake-site
            
            # Start/restart container with new image
            docker compose up -d
            
            # Clean up dangling images to save space
            docker rmi $(docker images -f "dangling=true" -q) 2>/dev/null || true
            
            echo "Deployment completed successfully!"
