# .github/workflows/deploy.yml
name: Deploy to Unraid Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, unraid-paul-blake]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # ... [Your Docker build steps remain the same] ...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        # ... [Your build config remains the same] ...
        
      # Use webfactory/ssh-agent with the RAW private key
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RAW }} # <-- Use the new RAW key secret

      # The deploy script now uses the agent automatically
      - name: Deploy to Unraid Server
        run: |
          # Add Unraid host to known_hosts to prevent interactive prompt
          ssh-keyscan -H ${{ secrets.UNRAID_HOST }} >> ~/.ssh/known_hosts
          
          # Use standard SSH. The agent will handle authentication.
          ssh ${{ secrets.UNRAID_USERNAME }}@${{ secrets.UNRAID_HOST }} << 'EOF'
            set -e # Exit script on any error
            echo "--- Navigating to project directory ---"
            cd /mnt/user/appdata/paul-blake-website/
            
            echo "--- Pulling latest image from Docker Hub ---"
            docker compose pull paul-blake-site
            
            echo "--- Restarting container with new image ---"
            docker compose up -d
            
            echo "--- Cleaning up old images ---"
            docker image prune -f
            
            echo "--- Deployment completed successfully! ---"
          EOF
